name 'solr-cloud-cluster'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures solr-cloud-cluster'
long_description 'Installs/Configures solr-cloud-cluster'
version '0.1.1'

depends 'java'
depends 'chef-provisioning-vagrant-helper'
depends 'zookeeper'
depends 'hostsfile'
depends 'solr'
